# Generated by Django 4.0.4 on 2022-05-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_auto_20181204_0441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pic',
        ),
        migrations.AddField(
            model_name='book',
            name='large_pic',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='small_pic',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='short',
            field=models.CharField(default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(default='English', help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)", max_length=200),
        ),
    ]
