# Generated by Django 4.0.4 on 2022-05-11 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0020_alter_student_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Circulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EachBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BID', models.IntegerField()),
                ('present', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=10)),
                ('total_books_due', models.IntegerField(default=0)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pic', models.ImageField(blank=True, upload_to='profile_image')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.department')),
                ('username', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(blank=True, null=True)),
                ('issue', models.BooleanField(blank=True, default=False, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='book',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='student',
        ),
        migrations.RemoveField(
            model_name='book',
            name='summary',
        ),
        migrations.AddField(
            model_name='student',
            name='yoj',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Borrower',
        ),
        migrations.DeleteModel(
            name='reviews',
        ),
        migrations.AddField(
            model_name='transfers',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.book'),
        ),
        migrations.AddField(
            model_name='transfers',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.student'),
        ),
        migrations.AddField(
            model_name='eachbook',
            name='isbn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.book'),
        ),
        migrations.AddField(
            model_name='circulation',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.book'),
        ),
        migrations.AddField(
            model_name='circulation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.student'),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(blank=True, null=True, to='management.author'),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.department'),
        ),
    ]
