# Generated by Django 4.0.4 on 2022-05-11 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_author_circulation_department_eachbook_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='branch',
        ),
    ]
