# Generated by Django 4.0.4 on 2022-05-14 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_remove_student_branch_remove_teacher_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circulation',
            name='book',
        ),
        migrations.RemoveField(
            model_name='circulation',
            name='student',
        ),
        migrations.RemoveField(
            model_name='transfers',
            name='issue',
        ),
        migrations.AddField(
            model_name='circulation',
            name='transfer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.transfers'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
