# Generated by Django 4.0.4 on 2022-05-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_remove_circulation_book_remove_circulation_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eachbook',
            name='BID',
            field=models.CharField(max_length=10),
        ),
    ]
