# Generated by Django 4.0.4 on 2022-05-14 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_alter_eachbook_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfers',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.eachbook'),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.student'),
        ),
    ]
