# Generated by Django 4.0.4 on 2022-05-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_alter_transfers_book_alter_transfers_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='total_books_due',
            field=models.IntegerField(default=1),
        ),
    ]
