# Generated by Django 4.0.4 on 2022-05-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_alter_student_total_books_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='available_copies',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
