# Generated by Django 4.0.4 on 2022-05-15 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_alter_book_available_copies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eachbook',
            old_name='isbn',
            new_name='book',
        ),
        migrations.RemoveField(
            model_name='eachbook',
            name='BID',
        ),
    ]
